### ISSUE TITLE
docker-compose up gives error, says I need to provide Project ID

### ISSUE THREAD

**Issue by PrashantSaikia** [amjadraza/langchain-chainlit-docker-deployment-template#2]
This is what I get when I run:

```
>>> docker-compose up
time="2023-10-31T12:40:57+01:00" level=warning msg="The \"OT\" variable is not set. Defaulting to a blank string."
time="2023-10-31T12:40:57+01:00" level=warning msg="The \"OT\" variable is not set. Defaulting to a blank string."
time="2023-10-31T12:40:57+01:00" level=warning msg="The \"OT\" variable is not set. Defaulting to a blank string."
Attaching to v12-langchain-chainlit-chat-app-1
v12-langchain-chainlit-chat-app-1  | Traceback (most recent call last):
v12-langchain-chainlit-chat-app-1  |   File "/app/.venv/bin/chainlit", line 5, in <module>
v12-langchain-chainlit-chat-app-1  |     from chainlit.cli import cli
v12-langchain-chainlit-chat-app-1  |   File "/app/.venv/lib/python3.11/site-packages/chainlit/__init__.py", line 8, in <module>
v12-langchain-chainlit-chat-app-1  |     from chainlit.config import config
v12-langchain-chainlit-chat-app-1  |   File "/app/.venv/lib/python3.11/site-packages/chainlit/config.py", line 213, in <module>
v12-langchain-chainlit-chat-app-1  |     config = load_config()
v12-langchain-chainlit-chat-app-1  |              ^^^^^^^^^^^^^
v12-langchain-chainlit-chat-app-1  |   File "/app/.venv/lib/python3.11/site-packages/chainlit/config.py", line 189, in load_config
v12-langchain-chainlit-chat-app-1  |     raise ValueError("Project ID is required when public is set to false.")
v12-langchain-chainlit-chat-app-1  | ValueError: Project ID is required when public is set to false.
v12-langchain-chainlit-chat-app-1 exited with code 1
```

Where do I find the project ID, and with what name do I need to give the project ID in the .env file? I tried `CHAINLIT_PROJECT_ID=xxxxxxxxxx`, but that did not work.

---

Also, `DOCKER_BUILDKIT` does not work on Windows. I keep getting this error:

`'DOCKER_BUILDKIT' is not recognized as an internal or external command,
operable program or batch file.`

That's why I did the docker build without DOCKER_BUILDKIT. Could that be why docker compose is not working?

**Comment by samixp02** [comment]
I think the error is clear public is set to false in the config file of chainlit  about your second question it's not related anyway you can try buildx instead if I'm not wrong
